table New_Measures
	lineageTag: 65aea866-3ed6-4e07-9d3e-930c59ae9a31

	measure 'Total Revenue' = SUM(pizza_sales[total_price])
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 7e56c090-6e86-498b-aa6e-f399f8e7f77d

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Total Number of Orders' = DISTINCTCOUNT(pizza_sales[order_id] )
		formatString: 0
		lineageTag: e2f6b54f-97c0-4266-98c2-0083190b177b

	measure 'Average Order Value' = DIVIDE([Total Revenue],[Total Number of Orders])
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: ca094964-b3b8-4d4c-96e0-eecc8763d9f3

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'Total Pizza''s Sold' = SUM(pizza_sales[quantity])
		formatString: 0
		lineageTag: 3f99ec4e-2ecc-4c3e-8253-cddd5098c01f

	measure 'Average Pizza''s Per Order' = DIVIDE([Total Pizza's Sold],[Total Number of Orders])
		lineageTag: 2b16e30e-2501-4f47-a805-94c14ca8865b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Target Goal' = SUM(pizza_sales[total_price])*1.5
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: fd684f05-12c8-4457-8331-cbfe07d91e92

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	column Column1
		dataType: string
		lineageTag: ec30d29c-61bc-44b6-ab0a-add5b209e9b1
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition New_Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

